version: 2
jobs:
  lint_commits:
    docker:
      - image: busybox
    steps:
      - checkout
      - run: "true"

  lint_helm:
    docker:
      - image: docker.io/lachlanevenson/k8s-helm:v2.8.1
    steps:
      - checkout
      - run: helm lint --strict charts/zenko-zookeeper

  init:
    docker:
      - image: busybox
    steps:
      - run: "true"

  prepare_release:
    docker:
      - image: busybox
    steps:
      - run: "true"

  build:
    docker:
      - image: busybox
    steps:
      - run: "true"

  test:
    docker:
      - image: busybox
    steps:
      - run: "true"

  publish:
    docker:
      - image: busybox
    steps:
      - run: "true"

workflows:
  version: 2
  build_test_publish:
    jobs:
      - lint_commits
      - lint_helm
      - init:
          requires:
            - lint_commits
            - lint_helm

      - prepare_release:
          requires:
            - init

      - test:
          requires:
            - prepare_release

      - publish:
          requires:
            - prepare_release
            - test
          filters:
            branches:
              only:
                - master

