version: 2
jobs:
  pre_init:
    docker:
      - image: busybox
    steps:
      - run: "true"

  lint_commits:
    docker:
      - image: busybox
    steps:
      - checkout
      - run: "true"

  lint_helm:
    docker:
      - image: docker.io/lachlanevenson/k8s-helm:v2.8.1
    steps:
      - checkout
      # - run: helm lint --strict charts/zenko-zookeeper
      - run: "true"

  post_init:
    docker:
      - image: busybox
    steps:
      - run: "true"

  pre_prepare_release:
    docker:
      - image: busybox
    steps:
      - run: "true"

  post_prepare_release:
    docker:
      - image: busybox
    steps:
      - run: "true"

  pre_build:
    docker:
      - image: busybox
    steps:
      - run: "true"

  post_build:
    docker:
      - image: busybox
    steps:
      - run: "true"

  pre_test:
    docker:
      - image: busybox
    steps:
      - run: "true"

  helm_install:
    docker:
      - image: busybox
    steps:
      - run: "true"

  helm_test:
    docker:
      - image: busybox
    steps:
      - run: "true"

  docker_image_tests:
    docker:
      - image: busybox
    steps:
      - run: "true"

  container_tools_image_tests:
    docker:
      - image: busybox
    steps:
      - run: "true"

  post_test:
    docker:
      - image: busybox
    steps:
      - run: "true"

  pre_publish:
    docker:
      - image: busybox
    steps:
      - run: "true"

  post_publish:
    docker:
      - image: busybox
    steps:
      - run: "true"

workflows:
  version: 2
  build_test_publish:
    jobs:
      - pre_init
      - lint_commits:
          requires:
            - pre_init
      - lint_helm:
          requires:
            - pre_init
      - post_init:
          requires:
            - pre_init
            - lint_commits
            - lint_helm

      - pre_prepare_release:
          requires:
            - post_init
      - post_prepare_release:
          requires:
            - pre_prepare_release

      - pre_test:
          requires:
            - post_prepare_release

      - helm_install:
          requires:
            - pre_test

      - helm_test:
          requires:
            - pre_test
            - helm_install

      - docker_image_tests:
          requires:
            - pre_test

      - container_tools_image_tests:
          requires:
            - pre_test

      - post_test:
          requires:
            - pre_test
            - helm_install
            - helm_test
            - docker_image_tests
            - container_tools_image_tests

      - pre_publish:
          requires:
            - post_test
          filters:
            branches:
              only:
                - master

      - post_publish:
          requires:
            - pre_publish
          filters:
            branches:
              only:
                - master
